import type { AdaptiveModuleId, AdaptiveModulePolicy } from './types';

export const ADAPTIVE_MODULE_POLICIES: Record<AdaptiveModuleId, AdaptiveModulePolicy> = {
  MOD_STRUCTURAL_READABILITY: {
    moduleId: 'MOD_STRUCTURAL_READABILITY',
    featureKinds: ['CHARACTER_PATTERN', 'LEXEME'],
    learnableLabels: ['OCR_GARBLED_CHARS', 'MISSING_MANDATORY_CONTACT'],
    minDocumentSupport: 3,
    minAbsZScore: 1.25,
    minLift: 1.6,
    maxRuntimeInfluence: 0.12,
    allowAutomaticActivation: false,
    notes: 'Uczy sygnały uszkodzeń OCR i ekstrakcji. Nie może oceniać jakości merytorycznej CV.',
  },
  MOD_JOB_ALIGNMENT: {
    moduleId: 'MOD_JOB_ALIGNMENT',
    featureKinds: ['LEXEME', 'ROLE_TITLE'],
    learnableLabels: ['CAREER_PIVOT_DISCONNECT'],
    minDocumentSupport: 4,
    minAbsZScore: 1.5,
    minLift: 1.8,
    maxRuntimeInfluence: 0.08,
    allowAutomaticActivation: false,
    notes: 'Rozszerza słownik aliasów i sygnałów domenowych, ale nie może sam promować RELATED_TECH do spełnienia MUST.',
  },
  MOD_FORMAL_REQUIREMENTS: {
    moduleId: 'MOD_FORMAL_REQUIREMENTS',
    featureKinds: ['FORMAL_TERM', 'LEXEME'],
    learnableLabels: ['FOREIGN_LANGUAGE_HALLUCINATION'],
    minDocumentSupport: 3,
    minAbsZScore: 1.4,
    minLift: 1.7,
    maxRuntimeInfluence: 0.08,
    allowAutomaticActivation: false,
    notes: 'Uczy warianty nazw certyfikatów, uprawnień, poziomów językowych i edukacji. Aktywacja wymaga jawnej walidacji.',
  },
  MOD_SKILL_RECENCY: {
    moduleId: 'MOD_SKILL_RECENCY',
    featureKinds: ['TEMPORAL_PATTERN', 'LEXEME'],
    learnableLabels: ['FUTURE_DATES_ANACHRONISM', 'IMPOSSIBLE_TECH_AGE'],
    minDocumentSupport: 3,
    minAbsZScore: 1.4,
    minLift: 1.7,
    maxRuntimeInfluence: 0.08,
    allowAutomaticActivation: false,
    notes: 'Uczy formaty temporalne i anomalie chronologiczne; krzywa zaniku pozostaje parametrem matematycznie kalibrowanym.',
  },
  MOD_ROLE_ALIGNMENT: {
    moduleId: 'MOD_ROLE_ALIGNMENT',
    featureKinds: ['ROLE_TITLE', 'LEXEME'],
    learnableLabels: ['SENIOR_CAMOUFLAGE_IMPOSTOR', 'OVERQUALIFIED_ACADEMIC_DRIFT', 'CIRCULAR_DEPENDENCY_ROLE'],
    minDocumentSupport: 3,
    minAbsZScore: 1.35,
    minLift: 1.6,
    maxRuntimeInfluence: 0.1,
    allowAutomaticActivation: false,
    notes: 'Buduje słownik tytułów, aliasów i sygnałów seniority. Nigdy nie ustala poziomu wyłącznie na podstawie jednego tytułu.',
  },
  MOD_IMPACT_QUANTIFICATION: {
    moduleId: 'MOD_IMPACT_QUANTIFICATION',
    featureKinds: ['NUMERIC_CONTEXT', 'LEXEME'],
    learnableLabels: ['ZERO_QUANTIFICATION_PASSIVE'],
    minDocumentSupport: 3,
    minAbsZScore: 1.25,
    minLift: 1.6,
    maxRuntimeInfluence: 0.12,
    allowAutomaticActivation: false,
    notes: 'Uczy kontekst liczb. Daty, staż, wersje, ceny nazw własnych i numery identyfikacyjne nie są automatycznie metrykami wpływu.',
  },
  MOD_LINGUISTIC_NATURALNESS: {
    moduleId: 'MOD_LINGUISTIC_NATURALNESS',
    featureKinds: ['LEXEME', 'CHARACTER_PATTERN'],
    learnableLabels: ['EXTREME_KEYWORD_STUFFING', 'OCR_GARBLED_CHARS'],
    minDocumentSupport: 3,
    minAbsZScore: 1.35,
    minLift: 1.7,
    maxRuntimeInfluence: 0.1,
    allowAutomaticActivation: false,
    notes: 'Uczy nienaturalne powtórzenia i n-gramy. OCR jest sygnałem niepewności, nie dowodem stuffing.',
  },
  MOD_FACT_CONSISTENCY: {
    moduleId: 'MOD_FACT_CONSISTENCY',
    featureKinds: ['TEMPORAL_PATTERN', 'ROLE_TITLE', 'LEXEME'],
    learnableLabels: ['FUTURE_DATES_ANACHRONISM', 'INVERTED_TIMELINE', 'EXTREME_CONCURRENT_EMPLOYMENT', 'IMPOSSIBLE_TECH_AGE'],
    minDocumentSupport: 3,
    minAbsZScore: 1.4,
    minLift: 1.7,
    maxRuntimeInfluence: 0.1,
    allowAutomaticActivation: false,
    notes: 'Uczy wzorce anomalii, ale sprzeczność musi być oparta na faktach i datach, nie samym leksemie.',
  },
  MOD_APPLICATION_READINESS: {
    moduleId: 'MOD_APPLICATION_READINESS',
    featureKinds: ['CALIBRATION_ONLY', 'FORMAL_TERM', 'TEMPORAL_PATTERN'],
    learnableLabels: ['MISSING_MANDATORY_CONTACT', 'UNEXPLAINED_MASSIVE_GAP'],
    minDocumentSupport: 4,
    minAbsZScore: 1.5,
    minLift: 1.8,
    maxRuntimeInfluence: 0.06,
    allowAutomaticActivation: false,
    notes: 'Kalibruje READY / READY_WITH_WARNINGS / NOT_READY z kontrolowanym zbiorem. Nie uczy prawdopodobieństwa zatrudnienia.',
  },
  MOD_CVELOCITY_CONSENSUS: {
    moduleId: 'MOD_CVELOCITY_CONSENSUS',
    featureKinds: ['CALIBRATION_ONLY'],
    learnableLabels: [],
    minDocumentSupport: 8,
    minAbsZScore: 2,
    minLift: 2,
    maxRuntimeInfluence: 0,
    allowAutomaticActivation: false,
    notes: 'D17 nie uczy leksemów bezpośrednio. Uczy wyłącznie kalibrację wag i przedziałów na holdoucie po akceptacji modułów źródłowych.',
  },
};

export function getAdaptiveModulePolicy(moduleId: AdaptiveModuleId): AdaptiveModulePolicy {
  return ADAPTIVE_MODULE_POLICIES[moduleId];
}
