import { SeniorityLevel } from './types';

export interface LexiconBank {
  adjectives: Record<SeniorityLevel, string[]>;
  achieveVerbs: Record<string, string[]>;
  connectors: string[];
  impactPhrases: Record<string, string[]>;
  valuePrefixes: string[];
}

export const LEXICON: LexiconBank = {
  adjectives: {
    junior: [
      'ambitny i zmotywowany',
      'dokładny i systematyczny',
      'szybko uczący się i zaangażowany',
      'skoncentrowany na rozwoju',
      'dociekliwy i sumienny',
      'otwarty na nową wiedzę techniczną',
      'skrupulatny w realizacji powierzonych zadań',
      'zdyscyplinowany i punktualny',
      'zaangażowany w podnoszenie kwalifikacji',
      'elastyczny i zorientowany na współpracę',
      'dbający o szczegóły i standardy',
      'gotowy do podejmowania nowych wyzwań',
    ],
    mid: [
      'samodzielny i rzetelny',
      'zorientowany na wysoką jakość',
      'doświadczony i skrupulatny',
      'efektywny i pragmatyczny',
      'odpowiedzialny i elastyczny w działaniu',
      'dbający o standardy techniczne i procedury',
      'zorientowany na optymalizację i porządek',
      'sprawnie rozwiązujący problemy techniczne',
      'komunikatywny i zorganizowany',
      'proaktywny i ukierunkowany na cel',
      'precyzyjny w realizacji harmonogramów',
      'posiadający ugruntowaną wiedzę praktyczną',
    ],
    senior: [
      'doświadczony i wszechstronny',
      'zaawansowany merytorycznie',
      'wysoko wykwalifikowany',
      'ekspercki i zorientowany na rezultaty',
      'posiadający wieloletnią praktykę branżową',
      'biegły w diagnozowaniu złożonych problemów',
      'ukierunkowany na prewencję i eliminację awarii',
      'autonomiczny w podejmowaniu decyzji technicznych',
      'rzetelny ekspert w swojej dziedzinie',
      'łączący wiedzę inżynieryjną z praktyką warsztatową',
      'zorientowany na optymalizację kosztową i jakość',
      'precyzyjny analityk procesów wykonawczych',
    ],
    lead: [
      'strategiczny i decyzyjny',
      'doświadczony lider i mentor',
      'zorientowany na architekturę i cele biznesowe',
      'kompleksowo zarządzający projektami',
      'skutecznie koordynujący pracę zespołu i brygad',
      'odpowiedzialny za nadzór i odbiory techniczne',
      'doświadczony kierownik robót i projektów',
      'zorientowany na ciągłe doskonalenie i BHP',
      'sprawnie zarządzający budżetem i harmonogramem',
      'budujący kulturę odpowiedzialności i zaangażowania',
      'reprezentujący firmę w kontaktach z inwestorami',
      'inicjujący usprawnienia organizacyjne i technologiczne',
    ],
  },

  achieveVerbs: {
    it: [
      'projektowałem i wdrażałem',
      'optymalizowałem i skalowałem',
      'zautomatyzowałem procesy oraz',
      'rozwijałem i modernizowałem',
      'integrowałem i zabezpieczałem',
      'optymalizowałem zapytania bazodanowe oraz',
      'konfigurowałem środowiska chmurowe oraz',
      'diagnozowałem błędy produkcyjne i',
      'zarządzałem wdrożeniami CI/CD oraz',
      'utrzymywałem wysoką dostępność systemów i',
      'standaryzowałem procesy wytwórcze oraz',
      'audytowałem bezpieczeństwo kodu i',
      'migrowałem bazy danych oraz',
      'modelowałem przepływy danych i',
      'testowałem automatycznie moduły oraz',
    ],
    trades: [
      'montowałem i serwisowałem',
      'diagnozowałem usterki i usuwałem',
      'prowadziłem prace instalacyjne oraz',
      'modernizowałem i kalibrowałem',
      'nadzorowałem eksploatację urządzeń oraz',
      'wykonywałem próby ciśnieniowe i',
      'prefabrykowałem rozdzielnice elektryczne oraz',
      'układałem i łączyłem instalacje sanitarne,',
      'spawałem konstrukcje stalowe metodami TIG/MAG i',
      'prowadziłem pomiary ochronne i odbiorcze oraz',
      'programowałem i nastawiałem sterowniki PLC,',
      'obsługiwałem obrabiarki CNC i',
      'realizowałem naprawy mechaniczne maszyn oraz',
      'nadzorowałem przestrzeganie przepisów BHP i DTR,',
      'regulowałem węzły cieplne i chłodnicze oraz',
      'wykonywałem przeglądy okresowe i remonty,',
    ],
    medical: [
      'prowadziłem diagnostykę i terapię',
      'wykonywałem procedury zabiegowe oraz',
      'koordynowałem opiekę medyczną i',
      'wdrażałem standardy kliniczne oraz',
      'prowadziłem dokumentację medyczną pacjentów i',
      'asystowałem przy skomplikowanych zabiegach oraz',
      'monitorowałem parametry życiowe i stan chorych,',
      'pobierałem materiał do badań laboratoryjnych oraz',
      'prowadziłem rehabilitację i terapię ruchową,',
      'nadzorowałem proces sterylizacji i aseptyki oraz',
      'edukowałem pacjentów w zakresie profilaktyki zdrowotnej i',
      'zarządzałem obiegiem leków na oddziale oraz',
      'przeprowadzałem wywiady epidemiologiczne i badania przesiewowe,',
      'podejmowałem natychmiastowe działania ratunkowe oraz',
      'uczestniczyłem w konsyliach specjalistycznych i',
    ],
    sales: [
      'budowałem relacje biznesowe i pozyskiwałem',
      'negocjowałem kontrakty handlowe oraz',
      'skalowałem wolumen sprzedaży i',
      'zarządzałem portfelem kluczowych klientów oraz',
      'analizowałem trendy rynkowe i potencjał zakupowy,',
      'przygotowywałem kompleksowe oferty techniczno-handlowe oraz',
      'koordynowałem procesy przetargowe i zapytania ofertowe,',
      'optymalizowałem marżowość realizowanych zleceń oraz',
      'prowadziłem prezentacje produktowe i demonstracje techniczne,',
      'reaktywowałem relacje z nieaktywnymi kontrahentami oraz',
      'zarządzałem lejkiem sprzedażowym w systemie CRM,',
      'tworzyłem plany sprzedażowe i prognozy przychodowe oraz',
      'nadzorowałem realizację zamówień i terminowość płatności,',
      'pozyskiwałem strategicznych partnerów dystrybucyjnych oraz',
      'badałem poziom satysfakcji klientów i wdrażałem usprawnienia,',
    ],
    general: [
      'optymalizowałem procedury i koordynowałem',
      'skutecznie realizowałem projekty oraz',
      'usprawniałem organizację pracy i',
      'wdrażałem nowe standardy,',
      'nadzorowałem zgodność operacyjną z przepisami oraz',
      'zarządzałem gospodarką magazynową i obiegiem materiałów,',
      'planowałem i egzekwowałem harmonogramy robót oraz',
      'redukowałem koszty operacyjne i straty materiałowe,',
      'szkoliłem pracowników i wdrażałem nowe kadry oraz',
      'rozliczałem czas pracy i zużycie zasobów,',
      'weryfikowałem jakość dostaw i surowców oraz',
      'przygotowywałem zestawienia i raporty dla dyrekcji,',
      'reorganizowałem stanowiska pracy zgodnie z zasadami ergonomii i',
      'koordynowałem współpracę z podwykonawcami oraz',
      'prowadziłem audyty wewnętrzne i kontrole jakościowe,',
    ],
  },

  connectors: [
    'ze szczególnym naciskiem na',
    'ze specjalizacją w obszarze',
    'ukierunkowany na',
    'specjalizujący się w zakresie',
    'zorientowany na efektywność w',
    'ze szczególnym uwzględnieniem',
    'z naciskiem na niezawodność i',
    'w oparciu o najlepsze praktyki w dziedzinie',
    'koncentrując się na precyzji w',
    'z dbałością o najwyższe standardy w',
    'łącząc wiedzę teoretyczną z praktyką w',
    'kładąc nacisk na bezpieczeństwo oraz',
    'ze szczególną dbałością o detale w',
    'specjalizując się w diagnostyce oraz',
    'ze stałym naciskiem na terminowość w',
  ],

  impactPhrases: {
    it: [
      'skracając czas wdrożeń i podnosząc stabilność',
      'obniżając koszty infrastruktury i usuwając dług techniczny',
      'zwiększając niezawodność systemów i zadowolenie użytkowników',
      'eliminując wąskie gardła w architekturze',
      'podnosząc pokrycie testami i redukując liczbę defektów',
      'zwiększając przepustowość przetwarzania danych w czasie rzeczywistym',
      'optymalizując czas odpowiedzi serwisów pod obciążeniem',
      'gwarantując wysoki poziom bezpieczeństwa teleinformatycznego',
      'automatyzując powtarzalne czynności wdrożeniowe i administracyjne',
      'usprawniając wymianę informacji w strukturach rozproszonych',
      'zmniejszając wskaźnik awaryjności i czas przywracania usług (MTTR)',
      'osiągając 99,9% dostępności krytycznych usług produkcyjnych',
    ],
    trades: [
      'minimalizując przestoje techniczne i gwarantując bezawaryjność',
      'zapewniając pełną zgodność z normami BHP i dokumentacją',
      'skracając czas realizacji prac montażowych',
      'podnosząc bezpieczeństwo i kulturę techniczną',
      'eliminując straty materiałowe i nieszczelności instalacji',
      'gwarantując precyzję wykonania zgodną ze sztuką budowlaną',
      'zapewniając bezproblemowe odbiory UDT i nadzoru budowlanego',
      'zwiększając żywotność maszyn dzięki regularnej konserwacji prewencyjnej',
      'obniżając koszty eksploatacji i zużycie energii w obiektach',
      'podnosząc wydajność linii produkcyjnych bez kompromisów jakościowych',
      'utrzymując ciągłość pracy węzłów technologicznych i agregatów',
      'zapobiegając kosztownym awariom poprzez trafną wibrodiagnostykę',
    ],
    medical: [
      'zapewniając najwyższy standard bezpieczeństwa pacjentów',
      'zgodnie z najnowszymi wytycznymi evidence-based medicine',
      'usprawniając obieg dokumentacji i procedury oddziałowe',
      'skracając czas oczekiwania na wyniki badań diagnostycznych',
      'minimalizując ryzyko zakażeń szpitalnych i powikłań pozabiegowych',
      'podnosząc komfort i poczucie bezpieczeństwa chorych',
      'zwiększając skuteczność rehabilitacji pourazowej pacjentów',
      'gwarantując pełną zgodność z rygorystycznymi normami sanitarnymi',
      'optymalizując gospodarkę lekową i zużycie materiałów medycznych',
      'zapewniając precyzyjną komunikację z zespołem interdyscyplinarnym',
    ],
    sales: [
      'konsekwentnie realizując i przekraczając cele kwartalne',
      'zwiększając marżowość i retencję klientów B2B',
      'skracając cykl decyzyjny w procesie sprzedażowym',
      'zwiększając udział w rynku w strategicznych segmentach',
      'minimalizując wskaźnik utraty klientów (churn rate)',
      'budując długofalowe partnerstwa oparte na zaufaniu i rentowności',
      'zwiększając średnią wartość zamówienia i cross-selling',
      'usprawniając proces ofertowania i obsługi posprzedażowej',
      'identyfikując nowe niszowe rynki i możliwości ekspansji',
      'podnosząc konwersję na każdym etapie lejka handlowego',
    ],
    general: [
      'podnosząc efektywność operacyjną całego zespołu',
      'gwarantując terminowość i rzetelność realizacji zadań',
      'optymalizując koszty i czas wykonania procesów',
      'eliminując zbędne marnotrawstwo w duchu metodologii Lean',
      'podnosząc transparentność raportowania i wskaźników KPI',
      'poprawiając przepływ informacji pomiędzy działami organizacji',
      'zwiększając dyscyplinę budżetową i kontrolę wydatków',
      'zmniejszając ryzyko operacyjne poprzez wdrożenie procedur kontrolnych',
      'podnosząc satysfakcję użytkowników wewnętrznych i zewnętrznych',
      'zwiększając stabilność i skalowalność procesów wykonawczych',
    ],
  },

  valuePrefixes: [
    'W codziennej pracy stawiam na',
    'Wyróżnia mnie',
    'Kluczowym atutem jest',
    'Moim priorytetem pozostaje',
    'Fundamentem mojego podejścia jest',
    'W pracy zawodowej koncentruję się na',
    'Cechuje mnie przede wszystkim',
    'Naczelną zasadą w mojej praktyce jest',
    'Największy nacisk kładę na',
    'W każdym projekcie dbam o',
    'Moją mocną stroną jest',
    'Szczególną wagę przywiązuję do',
  ],
};
