/** Dane syntetyczne współdzielone przez testy reguł i ekranowy przegląd kwalifikacji. */
export const qualificationCases = [
  ['prawo jazdy A', 'prawo jazdy kat. A', 'Prawo jazdy kategorii A', 'Prawo jazdy kat. B', 'license_a'],
  ['prawo jazdy B', 'prawo jazdy kat. B', 'Prawo jazdy kat B', 'Prawo jazdy kat. C', 'license_b'],
  ['prawo jazdy C', 'prawo jazdy kat. C', 'Prawo jazdy kat. C', 'Prawo jazdy kat. B', 'license_c'],
  ['prawo jazdy C+E', 'prawo jazdy kat. C+E', 'Prawo jazdy kat. C+E', 'Prawo jazdy kat. C', 'license_ce'],
  ['prawo jazdy D', 'prawo jazdy kat. D', 'Prawo jazdy kat. D', 'Prawo jazdy kat. C', 'license_d'],
  ['SEP G1', 'uprawnienia SEP G1', 'SEP G-1 — eksploatacja', 'SEP G3 — eksploatacja', 'sep_g1'],
  ['SEP G2', 'uprawnienia SEP G2', 'SEP G 2 — dozór', 'SEP G1 — dozór', 'sep_g2'],
  ['SEP G3', 'uprawnienia SEP G3', 'SEP G3 — eksploatacja', 'SEP G1 — eksploatacja', 'sep_g3'],
  ['F-Gaz', 'certyfikat F-Gaz', 'Certyfikat F-GAS Personel', 'Doświadczenie w chłodnictwie bez certyfikatu F-Gaz', 'fgas'],
  ['UDT wózki', 'uprawnienia UDT na wózki widłowe', 'UDT II WJO — wózki widłowe', 'UDT na suwnice', 'udt_forklift'],
  ['UDT suwnice', 'uprawnienia UDT na suwnice', 'UDT — suwnice', 'UDT na wózki widłowe', 'udt_suwnice'],
  ['UDT podesty', 'uprawnienia UDT na podesty ruchome', 'UDT — podesty ruchome', 'UDT na wózki widłowe', 'udt_lift'],
  ['UDT urządzenia ciśnieniowe', 'uprawnienia UDT na urządzenia ciśnieniowe', 'UDT — urządzenia ciśnieniowe', 'UDT na suwnice', 'udt_pressure'],
  ['spawanie TIG', 'uprawnienia spawalnicze TIG', 'TIG 141 — uprawnienia spawalnicze', 'MAG 135 — uprawnienia spawalnicze', 'welding'],
  ['sanepid', 'książeczka sanepidowska', 'Aktualna książeczka sanitarno-epidemiologiczna', 'Aktualne badania lekarskie bez książeczki sanepidowskiej', 'sanepid'],
  ['HACCP', 'certyfikat HACCP', 'Certyfikat HACCP', 'Certyfikat CCNA', 'haccp'],
  ['badania lekarskie', 'orzeczenie lekarskie', 'Orzeczenie lekarskie', 'Książeczka sanepidowska', 'medical_clearance'],
  ['praca na wysokości', 'uprawnienia do pracy na wysokości', 'Uprawnienia do pracy na wysokości', 'Uprawnienia UDT na wózki widłowe', 'height_work'],
  ['certyfikat Azure', 'certyfikat Azure', 'Certyfikat Microsoft Azure', 'Praktyczna znajomość Azure bez certyfikatu', 'cloud_cert_azure'],
  ['Scrum Master', 'certyfikat PSM I', 'PSM I — Scrum.org', 'SM I i doświadczenie w agile', 'scrum_master'],
  ['Cisco CCNA', 'certyfikat CCNA', 'Cisco CCNA', 'Cisco CCNP', 'cisco_ccna'],
] as const;
